package com.satyam.session.ui.theme

import androidx.compose.ui.graphics.Color

// Minimalist Neutral Slate (Light)
val md_theme_light_primary = Color(0xFF18181B)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFF4F4F5)
val md_theme_light_onPrimaryContainer = Color(0xFF18181B)
val md_theme_light_secondary = Color(0xFF71717A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE4E4E7)
val md_theme_light_onSecondaryContainer = Color(0xFF27272A)
val md_theme_light_tertiary = Color(0xFF3F3F46)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF4F4F5)
val md_theme_light_onTertiaryContainer = Color(0xFF18181B)
val md_theme_light_error = Color(0xFFDC2626)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFEE2E2)
val md_theme_light_onErrorContainer = Color(0xFF7F1D1D)
val md_theme_light_background = Color(0xFFFAFAFA)
val md_theme_light_onBackground = Color(0xFF09090B)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF09090B)
val md_theme_light_surfaceVariant = Color(0xFFF4F4F5)
val md_theme_light_onSurfaceVariant = Color(0xFF71717A)
val md_theme_light_outline = Color(0xFFD4D4D8)
val md_theme_light_outlineVariant = Color(0xFFE4E4E7)
val md_theme_light_surfaceContainerHighest = Color(0xFFE4E4E7)
val md_theme_light_surfaceContainerHigh = Color(0xFFF4F4F5)
val md_theme_light_surfaceContainer = Color(0xFFFAFAFA)
val md_theme_light_surfaceContainerLow = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)

// Minimalist AMOLED Dark Tokens
val md_theme_dark_primary = Color(0xFFF4F4F5)
val md_theme_dark_onPrimary = Color(0xFF09090B)
val md_theme_dark_primaryContainer = Color(0xFF27272A)
val md_theme_dark_onPrimaryContainer = Color(0xFFF4F4F5)
val md_theme_dark_secondary = Color(0xFFA1A1AA)
val md_theme_dark_onSecondary = Color(0xFF09090B)
val md_theme_dark_secondaryContainer = Color(0xFF27272A)
val md_theme_dark_onSecondaryContainer = Color(0xFFE4E4E7)
val md_theme_dark_tertiary = Color(0xFFD4D4D8)
val md_theme_dark_onTertiary = Color(0xFF09090B)
val md_theme_dark_tertiaryContainer = Color(0xFF18181B)
val md_theme_dark_onTertiaryContainer = Color(0xFFF4F4F5)
val md_theme_dark_error = Color(0xFFF87171)
val md_theme_dark_onError = Color(0xFF450A0A)
val md_theme_dark_errorContainer = Color(0xFF7F1D1D)
val md_theme_dark_onErrorContainer = Color(0xFFFECACA)
val md_theme_dark_background = Color(0xFF09090B)
val md_theme_dark_onBackground = Color(0xFFF4F4F5)
val md_theme_dark_surface = Color(0xFF09090B)
val md_theme_dark_onSurface = Color(0xFFF4F4F5)
val md_theme_dark_surfaceVariant = Color(0xFF18181B)
val md_theme_dark_onSurfaceVariant = Color(0xFFA1A1AA)
val md_theme_dark_outline = Color(0xFF3F3F46)
val md_theme_dark_outlineVariant = Color(0xFF27272A)
val md_theme_dark_surfaceContainerHighest = Color(0xFF27272A)
val md_theme_dark_surfaceContainerHigh = Color(0xFF1E1E22)
val md_theme_dark_surfaceContainer = Color(0xFF141417)
val md_theme_dark_surfaceContainerLow = Color(0xFF0F0F12)
val md_theme_dark_surfaceContainerLowest = Color(0xFF09090B)

/** Preset colors for activity buckets — inspired by Google Calendar event colors. */
object BucketColors {
    val Green = Color(0xFF4CAF50)
    val Blue = Color(0xFF2196F3)
    val Amber = Color(0xFFFFC107)
    val Orange = Color(0xFFFF9800)
    val Red = Color(0xFFF44336)
    val Purple = Color(0xFF9C27B0)
    val Teal = Color(0xFF009688)
    val Pink = Color(0xFFE91E63)
    val Indigo = Color(0xFF3F51B5)
    val Cyan = Color(0xFF00BCD4)

    val all = listOf(Green, Blue, Amber, Orange, Red, Purple, Teal, Pink, Indigo, Cyan)
    val hexList = listOf(
        "#4CAF50", "#2196F3", "#FFC107", "#FF9800", "#F44336",
        "#9C27B0", "#009688", "#E91E63", "#3F51B5", "#00BCD4"
    )
}
